DROP DATABASE APPWHATS;

CREATE DATABASE APPWHATS;

USE APPWHATS;

CREATE TABLE USUARIO(
    ID_USUARIO BIGINT AUTO_INCREMENT PRIMARY KEY,
    LOGIN VARCHAR(200),
    SENHA VARCHAR(200),
    APELIDO VARCHAR(200)    
);

CREATE TABLE MENSAGEM(
    ID_MENSAGEM BIGINT AUTO_INCREMENT PRIMARY KEY,
    ID_USUARIO_REMETENTE BIGINT,
    ID_USUARIO_DESTINATARIO BIGINT,
    MENSAGEM VARCHAR(512)    
);

insert into USUARIO (LOGIN,SENHA,APELIDO) 
values ('aug','aug','Augusto');

insert into USUARIO (LOGIN,SENHA,APELIDO) 
values ('teste','teste','teste');